name: shipmanagerapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.8
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.2
  equatable: ^2.0.5         # For easy state comparison
  provider: ^6.0.5          # For state management
  hive: ^2.2.3              # For local storage
  hive_flutter: ^1.1.0      # Hive for Flutter
  flutter_slidable: ^3.0.0  # For swipeable list items
  fl_chart: ^0.62.0         # For charts and graphs
  path_provider: ^2.0.15    # For file system access
  http: ^0.13.6             # For API requests
  flutter_svg: ^2.0.5       # For SVG support
  shimmer: ^3.0.0           # For loading effects
  url_launcher: ^6.1.11     # For launching URLs
  connectivity_plus: ^4.0.1 # For network connectivity detection
  flutter_localizations:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
